# pubspec.yaml
name: diet_app            # ← inchangé
description: PRBD Tutorial App.
publish_to: 'none'
version: 0.0.1+1

environment:
  # remplace juste cette ligne ↓
  sdk: '>=3.0.0 <4.0.0'   # Dart 3 minimum

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  jwt_decoder: ^2.0.1
  hive_ce: ^2.6.0
  async: ^2.11.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  test: ^1.24.0
  data_table_2: ^2.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  shared_preferences_foundation: 2.5.3
  path_provider_windows: 2.2.1